[package]
name = "ros2_cmd_vel_publisher"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-core = "0.3.31"
r2r = "0.9"                                        # Use the latest version
tokio = { version = "1", features = ["full"] }
opencv = { version = "0.93.3", features = ["clang-runtime"] }                                    # you may adjust the version according to system library
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

