[package]
name = "rust-networking"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
futures = "0.3"
sha2 = "0.10.8"
hmac = "0.12.1"
hex = "0.4.3"
